name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up SonarQube Scanner
      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}  # تأكد من إضافة SONAR_TOKEN في GitHub secrets
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}  # تأكد من إضافة SONAR_HOST_URL في GitHub secrets

      # Run SonarQube analysis
      - name: Run SonarQube analysis
        run: sonar-scanner

